### ISSUE TITLE
Meta data

### ISSUE THREAD

**Issue by vio** [relative-ci/bundle-stats#344]
- [x] webpack - builtAt, hash
- [ ] utils - report date
- [ ] utils - get git commit data (commit, branch, message)
- [x] ui - JobsHeader component
- [x] ui - change job counting (baseline should be `1st`)
- [x] html-templates - add meta data
